import { acqRuntime } from '../../acquisition/runtime'
import { sampleClock } from '../eeg/sampleClock'
import { captureSystemClock } from '../eeg/systemClock'
import { EVENT_SCHEMA, type SessionEventRecord } from './contracts'
import { sessionHub } from './sessionHub'

/** Optional local test process; no events are generated by the browser itself. */
export function installTriggerTestReceiver(): () => void {
  if (!['localhost', '127.0.0.1'].includes(location.hostname)) return () => {}
  let disposed = false
  let socket: WebSocket | null = null
  let timer: ReturnType<typeof setTimeout> | undefined
  const seen = new Set<string>()
  const connect = () => {
    if (disposed) return
    const ws = new WebSocket('ws://127.0.0.1:8782')
    socket = ws
    ws.onmessage = async event => {
      const systemClock = captureSystemClock()
      const eeg = sampleClock.snapshot(systemClock.monotonicMs)
      const session = sessionHub.info
      const ready = acqRuntime.recorder.recording && session.active && !!eeg?.native
        && systemClock.monotonicMs - eeg.arrivalNowMs < 1000
      let msg: Record<string, unknown>
      try { msg = JSON.parse(String(event.data)) } catch { return }
      const reply = (value: object) => { if (ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(value)) }
      if (msg.type === 'status') {
        reply({ type: 'status', ready, session, systemClock, eeg })
        return
      }
      if (msg.type !== 'trigger_test' || typeof msg.eventId !== 'string'
        || !/^TRIGGER_TEST_[a-zA-Z0-9_-]+$/.test(msg.eventId) || msg.eventId.length > 100
        || msg.code !== 65533) return
      if (!ready || seen.has(msg.eventId)) {
        reply({ type: 'trigger_ack', eventId: msg.eventId, accepted: false,
          error: ready ? 'Duplicate event ID' : 'Browser must be recording live native EEG' })
        return
      }
      seen.add(msg.eventId)
      if (seen.size > 10000) seen.delete(seen.values().next().value!)
      const record: SessionEventRecord = { schema: EVENT_SCHEMA, type: 'external_trigger_test', experiment: 'trigger_test',
        subjectId: '', systemClock, perf_ms: systemClock.monotonicMs, t_ms: systemClock.monotonicMs,
        eeg, data: { ...msg, webSession: session } }
      sessionHub.logEvent(record)
      await sessionHub.flush()
      // This acknowledges reception + flush attempt. The runner separately verifies disk contents.
      reply({ type: 'trigger_ack', eventId: msg.eventId, accepted: true, systemClock, eeg, session })
    }
    ws.onclose = () => { if (!disposed) timer = setTimeout(connect, 2000) }
    ws.onerror = () => { /* Connection errors are expected while the test process is stopped. */ }
  }
  connect()
  return () => { disposed = true; clearTimeout(timer); socket?.close() }
}
